### PR TITLE
Added store reference to shopping list.

### PR DESCRIPTION
**Pull request by avareldev**
1. code and add tests that cover the created code. Your code should be warning-free.
   * [ ] tests existing
1. stick to PSR-2 and and don't reformat existing code.
   * [ ] code style check succesful

### CODE REVIEW

**Comment by avareldev** [comment]
The store seems to be mandatory for shopping lists now if the customer has a store attached.

This currently causes an api error
`$draft = new ShoppingListDraft();
        $draft->setName($locale, 'foobar'));
        $draft->setCustomer(CustomerReference::ofId($customer->getId()));
        $draft->setLineItems((new LineItemDraftCollection())->add(LineItemDraft::ofSku('SKUSKU')));
        $request = ShoppingListCreateRequest::ofDraft($draft);
        $client->execute($request);`

I am unable to fix the tests right now.

**Comment by avareldev** [comment]
The store seems to be mandatory for shopping lists now if the customer has a store attached.

This currently causes an api error
`$draft = new ShoppingListDraft();
        $draft->setName($locale, 'foobar'));
        $draft->setCustomer(CustomerReference::ofId($customer->getId()));
        $draft->setLineItems((new LineItemDraftCollection())->add(LineItemDraft::ofSku('SKUSKU')));
        $request = ShoppingListCreateRequest::ofDraft($draft);
        $client->execute($request);`

I am unable to fix the tests right now.

**Comment by jenschude** [comment]
It’s a bug on the API level and the respective team is fixing it.

Stores are not yet available for shopping lists, so I will close this ticket as a tracking issue has been opened at our support portal.

Thanks for the contribution anyway.

**Comment by jenschude** [comment]
As this has been officially release as a new feature. The PR #610 fixes this and will soon be released

**Comment by jenschude** [comment]
Released with v2.15.0

**Pull request closed without merging**
